[package]
name = "bridging-payment-vara-supply-app"
version.workspace = true
edition.workspace = true

[dependencies]
sails-rs.workspace = true
vft-treasury-client.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
gstd.workspace = true
