[package]
name = "bridging-payment-vara-supply-client"
version.workspace = true
edition.workspace = true

[dependencies]
mockall = { version = "0.12", optional = true }
sails-rs.workspace = true

[build-dependencies]
bridging-payment-vara-supply-app.workspace = true
sails-client-gen.workspace = true
sails-idl-gen.workspace = true

[features]
mocks = ["sails-rs/mockall", "dep:mockall"]
