[package]
name = "historical-proxy-app"
version = "0.1.0"
edition = "2021"

[dependencies]
sails-rs.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true

[dev-dependencies]
futures.workspace = true
gclient.workspace = true
gstd.workspace = true
gtest.workspace = true
sails-rs = { workspace = true, features = ["gtest"] }
tokio = { workspace = true, features = ["rt", "macros"] }
historical-proxy = { workspace = true, features = ["wasm-binary"] }
historical-proxy-client.workspace = true