[package]
name = "historical-proxy-app"
version = "0.1.0"
edition = "2021"

[dependencies]
sails-rs.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true

[dev-dependencies]
historical-proxy-client.workspace = true
historical-proxy = { workspace = true, features = ["wasm-binary"] }