[package]
name = "historical-proxy-app"
version.workspace = true
edition.workspace = true

[dependencies]
sails-rs.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
eth-events-common.workspace = true
ethereum-common.workspace = true

[dev-dependencies]
gtest.workspace = true
eth-events-common.workspace = true
eth-events-deneb = { workspace = true, features = ["wasm-binary"] }
eth-events-deneb-client.workspace = true
eth-events-electra-client.workspace = true
sails-rs = { workspace = true, features = ["gtest", "gclient", "debug"] }
tokio = { workspace = true, features = ["rt", "macros"] }
historical-proxy = { workspace = true, features = ["wasm-binary"] }
historical-proxy-client.workspace = true

[target.'cfg(all(target_arch = "wasm32", target_os = "none"))'.dependencies]
getrandom = { workspace = true, features = ["custom"] }
lazy_static = { workspace = true, features = ["spin_no_std"] }

[build-dependencies]
sails-client-gen.workspace = true
