[package]
name = "historical-proxy-app"
version = "0.1.0"
edition = "2021"

[dependencies]
sails-rs.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
ethereum-common.workspace = true
erc20-relay-client.workspace = true


[dev-dependencies]
futures.workspace = true
gclient.workspace = true
gstd.workspace = true
gtest.workspace = true
sails-rs = { workspace = true, features = ["gtest"] }
tokio = { workspace = true, features = ["rt", "macros"] }
historical-proxy = { workspace = true, features = ["wasm-binary"] }
historical-proxy-client.workspace = true
erc20-relay = { workspace = true, features = ["wasm-binary"] }
vft-manager = { workspace = true, features = ["wasm-binary"] }
vft-manager-client.workspace = true

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
getrandom = { workspace = true, features = ["custom"] }
lazy_static = { workspace = true, features = ["spin_no_std"] }


[build-dependencies]
sails-client-gen.workspace = true