[package]
name = "checkpoint-light-client-app"
version.workspace = true
edition.workspace = true

[dependencies]
ark-bls12-381 = { workspace = true, features = ["curve"] }
ark-ec.workspace = true
ark-scale.workspace = true
ark-serialize.workspace = true
circular-buffer.workspace = true
ethereum-common.workspace = true
gbuiltin-bls381.workspace = true
hex-literal.workspace = true
sails-rs.workspace = true
tree_hash_derive.workspace = true

[dev-dependencies]
hex-literal.workspace = true
