[package]
name = "checkpoint-light-client-app"
version.workspace = true
edition.workspace = true

[dependencies]
ark-bls12-381 = { workspace = true, features = ["curve"] }
ark-scale.workspace = true
ark-serialize.workspace = true
circular-buffer.workspace = true
ethereum-common.workspace = true
sails-rs.workspace = true

[dev-dependencies]
hex-literal.workspace = true
