[package]
name = "deploy-to-gear"
version.workspace = true
edition.workspace = true

[dependencies]
vft = { workspace = true, features = ["wasm-binary"] }
vft-client.workspace = true
vft-vara = { workspace = true, features = ["wasm-binary"] }
vft-vara-client.workspace = true

clap.workspace = true
dotenv.workspace = true
gear-common.workspace = true
gear-core.workspace = true
gclient.workspace = true
gsdk.workspace = true
hex.workspace = true
sails-rs = { workspace = true, features = ["gclient"] }
tokio.workspace = true
