[package]
name = "deploy-checkpoints"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
ark-serialize = { workspace = true, features = ["std"] }
checkpoint_light_client = { workspace = true, features = ["std"] }
checkpoint_light_client-io = { workspace = true, features = ["std"] }
clap.workspace = true
dotenv.workspace = true
ethereum_beacon_client.workspace = true
gclient.workspace = true
hex.workspace = true
parity-scale-codec.workspace = true
tokio.workspace = true
