[package]
name = "vft-gateway-app"
version.workspace = true
edition.workspace = true

[dependencies]
sails-rs.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
alloy-rlp.workspace = true
alloy-sol-types.workspace = true
ethereum-common.workspace = true
gstd.workspace = true
gbuiltin-eth-bridge.workspace = true
vft-client.workspace = true

[build-dependencies]
git-download.workspace = true
sails-client-gen.workspace = true