[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
remappings = [
    "forge-std/=dependencies/forge-std-1.16.2/src/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.6.1/",
    "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.6.1/",
]
evm_version = "osaka"
solc = "0.8.35"
optimizer = true
extra_output_files = ["irOptimized"]
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
revert_strings = "strip"
# Required for OpenZeppelin Foundry Upgrades:
# - https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
# Some warnings should be omitted:
# - https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/115
# - https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5577
ignored_warnings_from = [
    "dependencies/openzeppelin-foundry-upgrades-0.4.1/src/internal/Core.sol",
    "dependencies/openzeppelin-foundry-upgrades-0.4.1/src/internal/DefenderDeploy.sol",
    "dependencies/openzeppelin-foundry-upgrades-0.4.1/src/internal/StringFinder.sol",

    "dependencies/@openzeppelin-contracts-5.6.1/utils/cryptography/ECDSA.sol",
    "dependencies/@openzeppelin-contracts-5.6.1/utils/structs/EnumerableMap.sol",
    "dependencies/@openzeppelin-contracts-5.6.1/utils/structs/EnumerableSet.sol",

    "src/libraries/CustomEnumerableMap.sol",
    "test/libraries/CustomEnumerableMap.t.sol",
]

[dependencies]
forge-std = "1.16.2"
"@openzeppelin-contracts" = "5.6.1"
"@openzeppelin-contracts-upgradeable" = "5.6.1"
openzeppelin-foundry-upgrades = "0.4.1"

[fmt]
sort_imports = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
hoodi = "${HOODI_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
hoodi = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
