[package]
name = "vft-gateway"
version.workspace = true
edition.workspace = true

[dependencies]
vft-gateway-app = { path = "app" }

[build-dependencies]
vft-gateway-app = { path = "app" }
sails-rs = { workspace = true, features = ["wasm-builder"] }
sails-idl-gen.workspace = true

[dev-dependencies]
vft-gateway = { path = ".", features = ["wasm-binary"] }
vft-gateway-client = { path = "client" }
vft-client.workspace = true

sails-rs = { workspace = true, features = ["gtest"] }
tokio = { workspace = true, features = ["rt", "macros"] }
blake2.workspace = true
gear-core.workspace = true
gtest.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
extended_vft_wasm.workspace = true

[features]
wasm-binary = []
