[package]
name = "vft-gateway-app"
version.workspace = true
edition.workspace = true

[dependencies]
sails-rs.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
gstd.workspace = true
gbuiltin-bridge.workspace = true

[build-dependencies]
git-download.workspace = true
sails-client-gen.workspace = true

[dev-dependencies]
gclient.workspace = true
tokio.workspace = true
blake2.workspace = true
gear-core.workspace = true
primitive-types.workspace = true
extended_vft_wasm = { git = "https://github.com/gear-foundation/standards/", branch = "gstd-pinned-v1.5.0" }
