[package]
name = "vara-tokenizer"
version.workspace = true
edition.workspace = true

[dependencies]
vara-tokenizer-app = { path = "app" }

[build-dependencies]
vara-tokenizer-app = { path = "app" }
sails-rs = { workspace = true, features = ["wasm-builder"] }
sails-client-gen.workspace = true
sails-idl-gen.workspace = true

[dev-dependencies]
vara-tokenizer = { path = ".", features = ["wasm-binary"] }
vara-tokenizer-client = { path = "client" }
sails-rs = { workspace = true, features = ["gtest", "gclient"] }
tokio = { version = "1.39", features = ["rt", "macros"] }
gclient.workspace = true
gtest.workspace = true
vft-client = { path = "../vft-client" }

[features]
wasm-binary = []
