[package]
name = "wrapped-vara"
version.workspace = true
edition.workspace = true

[dependencies]
wrapped-vara-app.workspace = true

[build-dependencies]
wrapped-vara-app.workspace = true
sails-rs = { workspace = true, features = ["wasm-builder"] }
sails-client-gen.workspace = true
sails-idl-gen.workspace = true

[dev-dependencies]
wrapped-vara = { workspace = true, features = ["wasm-binary"] }
wrapped-vara-client.workspace = true
sails-rs = { workspace = true, features = ["gtest", "gclient"] }
tokio = { workspace = true, features = ["rt", "macros"] }
gclient.workspace = true
gtest.workspace = true

[features]
wasm-binary = []
