[package]
name = "intermediate-proof-storage"
version.workspace = true
edition.workspace = true

[dependencies]
prover.workspace = true

anyhow.workspace = true
plonky2.workspace = true
serde_json.workspace = true
