[package]
name = "vft-manager"
version.workspace = true
edition.workspace = true

[dependencies]
vft-manager-app = { path = "app" }

[build-dependencies]
vft-manager-app = { path = "app" }
sails-rs = { workspace = true, features = ["wasm-builder"] }
sails-idl-gen.workspace = true

[features]
wasm-binary = []
mocks = ["vft-manager-app/mocks"]
