[package]
name = "vft-manager"
version.workspace = true
edition.workspace = true

[dependencies]
vft-manager-app = { path = "app" }

[build-dependencies]
vft-manager-app = { path = "app" }
sails-rs = { workspace = true, features = ["wasm-builder"] }
sails-idl-gen.workspace = true

[dev-dependencies]
vft-manager = { path = ".", features = ["wasm-binary"] }
vft-manager-client = { path = "client" }
vft = { workspace = true, features = ["wasm-binary"] }
vft-client.workspace = true

alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
sails-rs = { workspace = true, features = ["gtest"] }
tokio = { workspace = true, features = ["rt", "macros"] }
blake2.workspace = true
gear-core.workspace = true
gtest.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
gclient.workspace = true

[features]
wasm-binary = []
mocks = ["vft-manager-app/mocks"]
