[package]
name = "vara-tokenizer-app"
version.workspace = true
edition.workspace = true

[dependencies]
sails-rs.workspace = true
vft-service.workspace = true

[build-dependencies]
sails-client-gen.workspace = true
