import { HexString } from '@gear-js/api';

const CONTRACT_ADDRESS = {
  VFT_MANAGER: import.meta.env.VITE_VFT_MANAGER_CONTRACT_ADDRESS as HexString,
  BRIDGING_PAYMENT: import.meta.env.VITE_BRIDGING_PAYMENT_CONTRACT_ADDRESS as HexString,

  ETH_BRIDGING_PAYMENT: import.meta.env.VITE_ETH_BRIDGING_PAYMENT_CONTRACT_ADDRESS as HexString,
  ERC20_MANAGER: import.meta.env.VITE_ERC20_MANAGER_CONTRACT_ADDRESS as HexString,

  ETH_MESSAGE_QUEUE: import.meta.env.VITE_ETH_MESSAGE_QUEUE_CONTRACT_ADDRESS as HexString,
  CHECKPOINT_CLIENT: import.meta.env.VITE_CHECKPOINT_CLIENT_CONTRACT_ADDRESS as HexString,
  HISTORICAL_PROXY: import.meta.env.VITE_HISTORICAL_PROXY_CONTRACT_ADDRESS as HexString,
} as const;

const ETH_BEACON_NODE_ADDRESS = import.meta.env.VITE_ETH_BEACON_NODE_ADDRESS as string;

export { CONTRACT_ADDRESS, ETH_BEACON_NODE_ADDRESS };
