[package]
name = "vft-treasury-app"
version.workspace = true
edition.workspace = true

[dependencies]
sails-rs.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
gstd = { workspace = true, features = ["debug"] }
gbuiltin-eth-bridge.workspace = true
vft-client.workspace = true
