[package]
name = "bridging_payment"
version = "0.1.0"
edition = "2021"

[dependencies]
sails-rtl.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
gstd.workspace = true
gbuiltin-bridge.workspace = true

[build-dependencies]
git-download.workspace = true
sails-client-gen.workspace = true