[package]
name = "bridging-payment"
version.workspace = true
edition.workspace = true

#[dependencies]
#sails-rs.workspace = true
#parity-scale-codec.workspace = true
#scale-info.workspace = true
#gstd.workspace = true
#gbuiltin-eth-bridge.workspace = true
#gear-wasm-instrument.workspace = true
#
#[build-dependencies]
#git-download.workspace = true
#sails-client-gen.workspace = true

[dependencies]
bridging-payment-app = { path = "app" }

[build-dependencies]
bridging-payment-app = { path = "app" }
sails-rs = { workspace = true, features = ["wasm-builder"] }
sails-idl-gen.workspace = true

[dev-dependencies]
bridging-payment = { path = ".", features = ["wasm-binary"] }
bridging-payment-client = { path = "client" }
sails-rs = { workspace = true, features = ["gtest"] }
tokio = { workspace = true, features = ["rt", "macros"] }

[features]
wasm-binary = []
