[package]
name = "erc20-relay-client"
version = "0.1.0"
edition = "2021"

[dependencies]
mockall = { version = "0.12", optional = true }
sails-rs = "0.4.0"

[build-dependencies]
erc20-relay-app.workspace = true
sails-client-gen = "0.4.0"
sails-idl-gen = "0.4.0"

[features]
mocks = ["sails-rs/mockall", "dep:mockall"]
