[package]
name = "erc20-relay-app"
version = "0.1.0"
edition = "2021"

[dependencies]
sails-rs = { git = "https://github.com/gear-tech/sails.git", rev = "aab08733ee9ccdb809dc9b29c57dd411b2b917b1" }
ethereum-common.workspace = true
alloy-rlp.workspace = true
alloy-sol-types = { workspace = true, features = ["json"] }
checkpoint_light_client-io.workspace = true

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
getrandom = { version = "0.2", default-features = false, features = ["custom"] }
lazy_static = { version = "1.1", features = ["spin_no_std"] }

[dev-dependencies]
erc20-relay-client.workspace = true
erc20-relay = { workspace = true, features = ["wasm-binary", "gas_calculation"] }
futures.workspace = true
gclient.workspace = true
gstd.workspace = true
sails-rs = { git = "https://github.com/gear-tech/sails.git", rev = "aab08733ee9ccdb809dc9b29c57dd411b2b917b1", features = ["gclient"] }
tokio = { workspace = true, features = ["rt", "macros"] }
hex-literal.workspace = true
hex.workspace = true

[build-dependencies]
sails-client-gen = { git = "https://github.com/gear-tech/sails.git", rev = "aab08733ee9ccdb809dc9b29c57dd411b2b917b1" }

[features]
gas_calculation = []
mocks = []
