

[package]
name = "historical-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
historical-proxy-app = { path = "app" }

[build-dependencies]
historical-proxy-app = { path = "app" }
sails-rs = { workspace = true, features = ["wasm-builder"] }
sails-idl-gen.workspace = true

[dev-dependencies]
historical-proxy = { path = ".", features = ["wasm-binary"] }
historical-proxy-client = { path = "client" }
sails-rs = { version = "0.6.2", features = ["gtest"] }
tokio = { version = "1.41", features = ["rt", "macros"] }

[features]
wasm-binary = []
