import { HexString } from '@gear-js/api';

import { getNetworkEnv } from '../utils';

const NODE_ADDRESS = getNetworkEnv('VARA_NODE_ADDRESSES');
const ARCHIVE_NODE_ADDRESS = getNetworkEnv('VARA_ARCHIVE_NODE_ADDRESSES');

const ETH_NODE_ADDRESS = getNetworkEnv('ETH_NODE_ADDRESSES');
const ETH_BEACON_NODE_ADDRESS = getNetworkEnv('ETH_BEACON_NODE_ADDRESSES');
const ETH_CHAIN_ID = getNetworkEnv('ETH_CHAIN_IDS', (value) => Number(value));

const INDEXER_ADDRESS = getNetworkEnv('INDEXER_ADDRESSES');

const BRIDGING_PAYMENT_CONTRACT_ADDRESS = getNetworkEnv<HexString>('BRIDGING_PAYMENT_CONTRACT_ADDRESSES');
const VFT_MANAGER_CONTRACT_ADDRESS = getNetworkEnv<HexString>('VFT_MANAGER_CONTRACT_ADDRESSES');

const ETH_BRIDGING_PAYMENT_CONTRACT_ADDRESS = getNetworkEnv<HexString>('ETH_BRIDGING_PAYMENT_CONTRACT_ADDRESSES');
const ERC20_MANAGER_CONTRACT_ADDRESS = getNetworkEnv<HexString>('ERC20_MANAGER_CONTRACT_ADDRESSES');

const ETH_MESSAGE_QUEUE_CONTRACT_ADDRESS = getNetworkEnv<HexString>('ETH_MESSAGE_QUEUE_CONTRACT_ADDRESSES');

export {
  NODE_ADDRESS,
  ARCHIVE_NODE_ADDRESS,
  ETH_NODE_ADDRESS,
  ETH_BEACON_NODE_ADDRESS,
  ETH_CHAIN_ID,
  INDEXER_ADDRESS,
  BRIDGING_PAYMENT_CONTRACT_ADDRESS,
  VFT_MANAGER_CONTRACT_ADDRESS,
  ETH_BRIDGING_PAYMENT_CONTRACT_ADDRESS,
  ERC20_MANAGER_CONTRACT_ADDRESS,
  ETH_MESSAGE_QUEUE_CONTRACT_ADDRESS,
};
