import { getEthNetwork } from '../utils';

import {
  NODE_ADDRESS,
  ARCHIVE_NODE_ADDRESS,
  ETH_NODE_ADDRESS,
  ETH_BEACON_NODE_ADDRESS,
  ETH_CHAIN_ID,
  INDEXER_ADDRESS,
  BRIDGING_PAYMENT_CONTRACT_ADDRESS,
  VFT_MANAGER_CONTRACT_ADDRESS,
  ETH_BRIDGING_PAYMENT_CONTRACT_ADDRESS,
  ERC20_MANAGER_CONTRACT_ADDRESS,
  ETH_MESSAGE_QUEUE_CONTRACT_ADDRESS,
} from './env';

const MAINNET_PRESET = {
  NODE_ADDRESS: NODE_ADDRESS.MAINNET,
  ARCHIVE_NODE_ADDRESS: ARCHIVE_NODE_ADDRESS.MAINNET,

  ETH_NODE_ADDRESS: ETH_NODE_ADDRESS.MAINNET,
  ETH_BEACON_NODE_ADDRESS: ETH_BEACON_NODE_ADDRESS.MAINNET,
  ETH_CHAIN_ID: ETH_CHAIN_ID.MAINNET,

  INDEXER_ADDRESS: INDEXER_ADDRESS.MAINNET,

  BRIDGING_PAYMENT_CONTRACT_ADDRESS: BRIDGING_PAYMENT_CONTRACT_ADDRESS.MAINNET,
  VFT_MANAGER_CONTRACT_ADDRESS: VFT_MANAGER_CONTRACT_ADDRESS.MAINNET,

  ETH_BRIDGING_PAYMENT_CONTRACT_ADDRESS: ETH_BRIDGING_PAYMENT_CONTRACT_ADDRESS.MAINNET,
  ERC20_MANAGER_CONTRACT_ADDRESS: ERC20_MANAGER_CONTRACT_ADDRESS.MAINNET,

  ETH_MESSAGE_QUEUE_CONTRACT_ADDRESS: ETH_MESSAGE_QUEUE_CONTRACT_ADDRESS.MAINNET,

  NETWORK_NAME: { VARA: 'Vara Mainnet', ETH: 'Ethereum Mainnet' },
  EXPLORER_URL: { VARA: 'https://vara.subscan.io', ETH: 'https://etherscan.io' },

  ETH_NETWORK: getEthNetwork(ETH_CHAIN_ID.MAINNET),
};

const TESTNET_PRESET = {
  NODE_ADDRESS: NODE_ADDRESS.TESTNET,
  ARCHIVE_NODE_ADDRESS: ARCHIVE_NODE_ADDRESS.TESTNET,

  ETH_NODE_ADDRESS: ETH_NODE_ADDRESS.TESTNET,
  ETH_BEACON_NODE_ADDRESS: ETH_BEACON_NODE_ADDRESS.TESTNET,
  ETH_CHAIN_ID: ETH_CHAIN_ID.TESTNET,

  INDEXER_ADDRESS: INDEXER_ADDRESS.TESTNET,

  BRIDGING_PAYMENT_CONTRACT_ADDRESS: BRIDGING_PAYMENT_CONTRACT_ADDRESS.TESTNET,
  VFT_MANAGER_CONTRACT_ADDRESS: VFT_MANAGER_CONTRACT_ADDRESS.TESTNET,

  ETH_BRIDGING_PAYMENT_CONTRACT_ADDRESS: ETH_BRIDGING_PAYMENT_CONTRACT_ADDRESS.TESTNET,
  ERC20_MANAGER_CONTRACT_ADDRESS: ERC20_MANAGER_CONTRACT_ADDRESS.TESTNET,

  ETH_MESSAGE_QUEUE_CONTRACT_ADDRESS: ETH_MESSAGE_QUEUE_CONTRACT_ADDRESS.TESTNET,

  NETWORK_NAME: { VARA: 'Vara Testnet', ETH: 'Ethereum Hoodi' },
  EXPLORER_URL: { VARA: undefined, ETH: 'https://hoodi.etherscan.io' },

  ETH_NETWORK: getEthNetwork(ETH_CHAIN_ID.TESTNET),
};

const NETWORK_PRESET = {
  MAINNET: MAINNET_PRESET,
  TESTNET: TESTNET_PRESET,
} as const;

export { NETWORK_PRESET };
