[package]
name = "ethereum-event-client"
version.workspace = true
edition.workspace = true

[dependencies]
ethereum-event-client-app.workspace = true

[build-dependencies]
ethereum-event-client-app.workspace = true
sails-rs = { workspace = true, features = ["wasm-builder"] }
sails-idl-gen.workspace = true

[features]
wasm-binary = []