[package]
name = "bridge-payment-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
bridge-payment.workspace = true

[build-dependencies]
gwasm-builder.workspace = true
sails-idl-gen.workspace = true