[package]
name = "vft-treasury"
version.workspace = true
edition.workspace = true

[dependencies]
vft-treasury-app = { path = "app" }

[build-dependencies]
vft-treasury-app = { path = "app" }
sails-rs = { workspace = true, features = ["wasm-builder"] }
sails-idl-gen.workspace = true

[dev-dependencies]
vft-treasury = { path = ".", features = ["wasm-binary"] }
vft-treasury-client = { path = "client" }
sails-rs = { workspace = true, features = ["gtest"] }
tokio = { version = "1.39", features = ["rt", "macros"] }

[features]
wasm-binary = []
