[package]
name = "ping"
version.workspace = true
edition.workspace = true

[dependencies]
sails-rs.workspace = true
parity-scale-codec = { workspace = true, default-features = false, features = [
    "derive",
] }
scale-info = { workspace = true, default-features = false }
alloy-rlp.workspace = true
alloy-sol-types.workspace = true
ethereum-common.workspace = true
gstd.workspace = true
gbuiltin-eth-bridge.workspace = true

[dev-dependencies]
alloy-consensus.workspace = true
alloy-primitives.workspace = true
gtest.workspace = true

[target.'cfg(all(target_arch = "wasm32", target_os = "none"))'.dependencies]
getrandom = { workspace = true, features = ["custom"] }
lazy_static = { workspace = true, features = ["spin_no_std"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sails-rs = { workspace = true, features = ["idl-gen"] }

[[bin]]
name = "ping-idl-gen"
path = "src/main-idl-gen.rs"

[build-dependencies]
sails-rs = { workspace = true, features = ["wasm-builder"] }
