constructor {
  New : ();
};

service Ping {
  SubmitReceipt : (slot: u64, transaction_index: u32, _receipt_rlp: vec u8) -> result (null, str);

  events {
    ReceiptSubmitted: struct {
      u64,
      u32,
    };
  }
};

