[package]
name = "vft_gateway_wasm"
version.workspace = true
edition.workspace = true 

[dependencies]
vft-gateway.workspace = true

[build-dependencies]
gwasm-builder.workspace = true
sails-idl-gen.workspace = true
vft-gateway.workspace = true

[dev-dependencies]
gtest.workspace = true
vft-gateway.workspace = true
extended_vft_wasm = { git = "https://github.com/gear-foundation/standards/"}
parity-scale-codec.workspace = true
scale-info.workspace = true
sails-rs.workspace = true