[package]
name = "vft_gateway_wasm"
version.workspace = true
edition.workspace = true 

[dependencies]
vft-gateway-app.workspace = true
sails-rs.workspace = true

[build-dependencies]
gwasm-builder.workspace = true
sails-idl-gen.workspace = true
vft-gateway-app.workspace = true
sails-client-gen.workspace = true

[dev-dependencies]
gtest.workspace = true
vft-gateway-app.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
sails-rs.workspace = true
tokio.workspace = true
blake2 = { version = "0.10.6", default-features = false }
gear-core.workspace = true
extended_vft_wasm.workspace = true
