[package]
name = "vft_gateway_wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
vft-gateway.workspace = true

[build-dependencies]
gwasm-builder.workspace = true
sails-idl-gen.workspace = true
vft-gateway.workspace = true

[lib]
crate-type = ["rlib"]
name = "vft_gateway_wasm"