type InitConfig = struct {
  receiver_contract_address: h160,
  gear_bridge_builtin: actor_id,
  config: Config,
};

type Config = struct {
  gas_to_burn_tokens: u64,
  gas_for_reply_deposit: u64,
  gas_to_mint_tokens: u64,
  gas_to_send_request_to_builtin: u64,
  reply_timeout: u32,
};

type Error = enum {
  SendError,
  ReplyError,
  BurnTokensDecodeError,
  ErrorDuringTokensBurn,
  RequestToBuiltinSendError,
  RequestToBuiltinReplyError,
  BuiltinDecodeError,
  PayloadSizeError,
  MintTokensDecodeError,
  ReplyTimeoutError,
  TokensRefundedError,
  ErrorDuringTokensMint,
  NoCorrespondingEthAddress,
  ReplyHook,
  MessageNotFound,
  InvalidMessageStatus,
  MessageFailed,
  BurnTokensFailed,
  BridgeBuiltinMessageFailed,
};

type MessageInfo = struct {
  status: MessageStatus,
  details: TransactionDetails,
};

type MessageStatus = enum {
  SendingMessageToBurnTokens,
  TokenBurnCompleted: bool,
  WaitingReplyFromBurn,
  SendingMessageToBridgeBuiltin,
  BridgeResponseReceived: opt u256,
  WaitingReplyFromBuiltin,
  BridgeBuiltinStep,
  SendingMessageToMintTokens,
  TokenMintCompleted,
  WaitingReplyFromMint,
  MintTokensStep,
  MessageProcessedWithSuccess: u256,
};

type TransactionDetails = struct {
  vara_token_id: actor_id,
  sender: actor_id,
  amount: u256,
  receiver: h160,
};

constructor {
  New : (init_config: InitConfig);
};

service VftGateway {
  HandleInterruptedTransfer : (msg_id: message_id) -> result (struct { u256, h160 }, Error);
  MapVaraToEthAddress : (vara_token_id: actor_id, eth_token_id: h160) -> null;
  TransferVaraToEth : (vara_token_id: actor_id, amount: u256, receiver: h160) -> result (struct { u256, h160 }, Error);
  UpdateReceiverContractAddress : (new_receiver_contract_address: h160) -> null;
  query Admin : () -> actor_id;
  query GearBridgeBuiltin : () -> actor_id;
  query GetConfig : () -> Config;
  query MsgTrackerState : () -> vec struct { message_id, MessageInfo };
  query ReceiverContractAddress : () -> h160;
  query VaraToEthAddresses : () -> vec struct { actor_id, h160 };
};

