// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2023 Snowfork <hello@snowfork.com>
pragma solidity 0.8.37;

// Used to verify merkle proofs generated by https://github.com/paritytech/substrate/tree/master/utils/binary-merkle-tree
library SubstrateMerkleProof {
    /**
     * @notice Verify that a specific leaf element is part of the Merkle Tree at a specific position in the tree
     *
     * The tree would have been constructed using
     * https://paritytech.github.io/substrate/master/binary_merkle_tree/fn.merkle_root.html
     *
     * This implementation adapted from
     * https://paritytech.github.io/substrate/master/binary_merkle_tree/fn.verify_proof.html
     *
     * @param root the root of the merkle tree
     * @param leaf the leaf which needs to be proven
     * @param position the position of the leaf, index starting with 0
     * @param width the width or number of leaves in the tree
     * @param proof the array of proofs to help verify the leaf's membership, ordered from leaf to root
     * @return a boolean value representing the success or failure of the operation
     */
    function verify(bytes32 root, bytes32 leaf, uint256 position, uint256 width, bytes32[] calldata proof)
        internal
        pure
        returns (bool)
    {
        (bool valid, bytes32 node) = computeRoot(leaf, position, width, proof);
        return valid && root == node;
    }

    function computeRoot(bytes32 leaf, uint256 position, uint256 width, bytes32[] calldata proof)
        internal
        pure
        returns (bool valid, bytes32 node)
    {
        if (position >= width) {
            return (false, bytes32(0));
        }

        node = leaf;
        uint256 proofIndex;
        unchecked {
            while (width > 1) {
                if ((position & 1) == 1) {
                    if (proofIndex >= proof.length) {
                        return (false, bytes32(0));
                    }
                    node = efficientHash(proof[proofIndex++], node);
                } else if (position + 1 < width) {
                    if (proofIndex >= proof.length) {
                        return (false, bytes32(0));
                    }
                    node = efficientHash(node, proof[proofIndex++]);
                }
                position >>= 1;
                width = (width >> 1) + (width & 1);
            }
        }
        return (proofIndex == proof.length, node);
    }

    function efficientHash(bytes32 a, bytes32 b) internal pure returns (bytes32 value) {
        /// @solidity memory-safe-assembly
        assembly {
            mstore(0x00, a)
            mstore(0x20, b)
            value := keccak256(0x00, 0x40)
        }
    }
}
