export const HistoricalProxyTypes = {
  EthToVaraEvent: {
    proof_block: "BlockInclusionProof",
    proof: "Vec<Vec<u8>>",
    transaction_index: "u64",
    receipt_rlp: "Vec<u8>",
  },
  BlockInclusionProof: {
    block: "BlockGenericForBlockBody",
    headers: "Vec<BlockHeader>",
  },
  BlockHeader: {
    slot: "u64",
    proposer_index: "u64",
    parent_root: "H256",
    state_root: "H256",
    body_root: "H256",
  },
  BlockGenericForBlockBody: {
    slot: "u64",
    proposer_index: "u64",
    parent_root: "H256",
    state_root: "H256",
    body: "BlockBody",
  },
  BlockBody: {
    randao_reveal: "H256",
    eth1_data: "H256",
    graffiti: "BytesFixed1",
    proposer_slashings: "H256",
    attester_slashings: "H256",
    attestations: "H256",
    deposits: "H256",
    voluntary_exits: "H256",
    sync_aggregate: "H256",
    execution_payload: "ExecutionPayload",
    bls_to_execution_changes: "H256",
    blob_kzg_commitments: "H256",
    execution_requests: "H256",
  },
  BytesFixed1: "(FixedArray1ForU8)",
  FixedArray1ForU8: "([u8; 32])",
  ExecutionPayload: {
    parent_hash: "BytesFixed1",
    fee_recipient: "BytesFixed2",
    state_root: "BytesFixed1",
    receipts_root: "BytesFixed1",
    logs_bloom: "H256",
    prev_randao: "BytesFixed1",
    block_number: "u64",
    gas_limit: "u64",
    gas_used: "u64",
    timestamp: "u64",
    extra_data: "ByteList",
    base_fee_per_gas: "U256",
    block_hash: "BytesFixed1",
    transactions: "H256",
    withdrawals: "H256",
    blob_gas_used: "u64",
    excess_blob_gas: "u64",
  },
  BytesFixed2: "(FixedArray2ForU8)",
  FixedArray2ForU8: "([u8; 20])",
  ByteList: "(ListForU8)",
  ListForU8: { data: "Vec<u8>" },
};
