[package]
name = "gear_proof_storage"
version.workspace = true
edition.workspace = true

[dependencies]
gstd.workspace = true
gear-wasm-instrument.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
thiserror.workspace = true

[build-dependencies]
gear-wasm-builder.workspace = true

[lib]
crate-type = ["rlib"]
name = "gear_proof_storage"

[features]
std = []
default = ["std"]
