[package]
name = "gear_proof_storage"
version.workspace = true
edition.workspace = true

[dependencies]
gstd.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
thiserror.workspace = true

[build-dependencies]
gear-wasm-builder.workspace = true

[features]
std = ["thiserror/std", "parity-scale-codec/std", "scale-info/std"]
default = ["std"]
