[package]
name = "vft-client"
version.workspace = true
edition.workspace = true

[dependencies]
mockall = { version = "0.12", optional = true }
sails-rs.workspace = true

[build-dependencies]
sails-client-gen.workspace = true

[features]
mocks = ["sails-rs/mockall", "dep:mockall"]
