[package]
name = "vft-manager-app"
version.workspace = true
edition.workspace = true

[dependencies]
sails-rs.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
alloy-rlp.workspace = true
alloy-sol-types = { workspace = true, features = ["json"] }
ethereum-common.workspace = true
gstd.workspace = true
gbuiltin-eth-bridge.workspace = true
extended-vft-client.workspace = true

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
getrandom = { workspace = true, features = ["custom"] }
lazy_static = { workspace = true, features = ["spin_no_std"] }

[build-dependencies]
git-download.workspace = true
sails-client-gen.workspace = true

[dev-dependencies]
anyhow.workspace = true
extended-vft = { workspace = true, features = ["wasm-binary"] }
extended-vft-client.workspace = true
futures.workspace = true
gclient.workspace = true
hex.workspace = true
sails-rs = { workspace = true, features = ["gclient"] }
sp-core = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["rt", "macros"] }
vft-manager = { workspace = true, features = ["wasm-binary"] }
vft-manager-client.workspace = true
