[package]
name = "checkpointeths-io"
version.workspace = true
edition.workspace = true

[dependencies]
ethereum-common.workspace = true
parity-scale-codec.workspace = true
serde.workspace = true
ark-serialize = { workspace = true }
ark-bls12-381 = { workspace = true, features = ["curve"] }
ark-scale.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
hex-literal.workspace = true
tree_hash_derive.workspace = true

[features]
default = ["std"]
std = [
    "ethereum-common/std",
    "parity-scale-codec/std",
    "serde/std",
    "ark-serialize/std",
    "ark-bls12-381/std",
    "ark-scale/std",
    "ark-ec/std",
    "ark-ff/std",
]
