[package]
name = "vft-client"
version.workspace = true
edition.workspace = true

[dependencies]
mockall = { workspace = true, optional = true }
sails-rs.workspace = true

[build-dependencies]
vft-app.workspace = true
sails-client-gen.workspace = true
sails-idl-gen.workspace = true

[features]
mocks = ["sails-rs/mockall", "dep:mockall"]
