[package]
name = "bridging-payment-app"
version.workspace = true
edition.workspace = true

[dependencies]
gear-programs-common = { workspace = true, features = ["wasm"] }

parity-scale-codec = { workspace = true, features = ["derive"] }
sails-rtl.workspace = true
scale-info = { workspace = true, features = ["derive"] }
