[package]
name = "bridging-payment-app"
version.workspace = true
edition.workspace = true

[dependencies]
vft-manager-client.workspace = true
sails-rs.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
gstd.workspace = true
