[package]
name = "eth-events-electra"
version.workspace = true
edition.workspace = true

[dependencies]
eth-events-electra-app.workspace = true

[build-dependencies]
eth-events-electra-app.workspace = true
sails-rs = { workspace = true, features = ["wasm-builder"] }
sails-idl-gen.workspace = true

[features]
wasm-binary = []