[package]
name = "vft-service"
version.workspace = true
edition.workspace = true

[dependencies]
gstd.workspace = true
log = "*"
sails-rs.workspace = true

[dev-dependencies]
env_logger.workspace = true
gtest.workspace = true
gear-core.workspace = true
