name: build_and_publish_relayer

on:
  workflow_call:
    inputs:
      tags:
        type: string

jobs:
  build:
    runs-on: kuberunner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to gchr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ inputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max