name: CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-publish-relayer:
    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    uses: ./.github/workflows/build-and-publish-relayer.yml
    with: 
      tags: ghcr.io/gear-tech/bridge-relayer:${{ github.ref_name }}.${{ github.sha }}

  build-and-publish-relayer-release:
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/build-and-publish-relayer.yml
    with: 
      tags: ghcr.io/gear-tech/bridge-relayer:latest,ghcr.io/gear-tech/bridge-relayer:${{ github.ref_name }}
