name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-publish-relayer:
    uses: ./.github/workflows/build-and-publish-relayer.yml
    with: 
      tags: ${{ github.ref_name }}.${{ github.sha }},latest
