name: Build and Deploy Bridge

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '.github/**'
      - '**.md'
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Target environment
        required: false
        options: [prod]
      deploy_mainnet-gear-indexer:
        type: boolean
        description: Build indexer
        default: true
      deploy_frontend:
        type: boolean
        description: Build frontend
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  packages: write
  actions: write
  id-token: write

jobs:
  deploy:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      app: bridge
      env: ${{ inputs.env }}
      components: |
        - name: mainnet-gear-indexer
          docker_file: js/indexer/Dockerfile
          docker_registry: ghcr.io/gear-tech/gear-bridges-indexer
          chart_components_extra: |
            mainnet-eth-indexer
            mainnet-explorer
          paths: |
            js/indexer/**
            js/common/**
            api/gear/**
            api/ethereum/**
            package.json
            yarn.lock
            lerna.json
            .yarnrc.yml
            .yarn/**
        - name: frontend
          docker_file: js/frontend/Dockerfile
          paths: |
            js/frontend/**
            js/common/**
            js/bridge-js/**
            package.json
            yarn.lock
            lerna.json
            .yarnrc.yml
            .yarn/**
    secrets:
      CHARTS_REPO_TOKEN: ${{ secrets.CHARTS_REPO_TOKEN }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
