name: Build and Deploy Bridge

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '.github/**'
      - '**.md'
    tags: ["*-v*"]
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Target environment
        required: false
        options:
          - dev
          - stg
          - prod
      deploy_mainnet_gear_indexer:
        type: boolean
        description: Deploy mainnet-gear-indexer
        default: true
      deploy_mainnet_eth_indexer:
        type: boolean
        description: Deploy mainnet-eth-indexer
        default: true
      deploy_mainnet_explorer:
        type: boolean
        description: Deploy mainnet-explorer
        default: true
      deploy_hoodi_gear_indexer:
        type: boolean
        description: Deploy hoodi-gear-indexer
        default: true
      deploy_hoodi_eth_indexer:
        type: boolean
        description: Deploy hoodi-eth-indexer
        default: true
      deploy_hoodi_explorer:
        type: boolean
        description: Deploy hoodi-explorer
        default: true
      deploy_frontend:
        type: boolean
        description: Deploy frontend
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  packages: write
  actions: write
  id-token: write

jobs:
  deploy_mainnet_gear_indexer:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      app: bridge
      component: mainnet-gear-indexer
      env: ${{ inputs.env }}
      dockerfile: js/indexer/Dockerfile
      context: .
      paths_filter: |
        js/indexer/**
        js/common/**
        api/gear/**
        package.json
        yarn.lock
        lerna.json
        .yarnrc.yml
        .yarn/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}

  deploy_mainnet_eth_indexer:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      app: bridge
      component: mainnet-eth-indexer
      env: ${{ inputs.env }}
      dockerfile: js/indexer/Dockerfile
      context: .
      paths_filter: |
        js/indexer/**
        js/common/**
        api/ethereum/**
        package.json
        yarn.lock
        lerna.json
        .yarnrc.yml
        .yarn/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}

  deploy_mainnet_explorer:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      app: bridge
      component: mainnet-explorer
      env: ${{ inputs.env }}
      dockerfile: js/indexer/Dockerfile
      context: .
      paths_filter: |
        js/indexer/**
        js/common/**
        package.json
        yarn.lock
        lerna.json
        .yarnrc.yml
        .yarn/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}

  deploy_hoodi_gear_indexer:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      app: bridge
      component: hoodi-gear-indexer
      env: ${{ inputs.env }}
      dockerfile: js/indexer/Dockerfile
      context: .
      paths_filter: |
        js/indexer/**
        js/common/**
        api/gear/**
        package.json
        yarn.lock
        lerna.json
        .yarnrc.yml
        .yarn/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}

  deploy_hoodi_eth_indexer:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      app: bridge
      component: hoodi-eth-indexer
      env: ${{ inputs.env }}
      dockerfile: js/indexer/Dockerfile
      context: .
      paths_filter: |
        js/indexer/**
        js/common/**
        api/ethereum/**
        package.json
        yarn.lock
        lerna.json
        .yarnrc.yml
        .yarn/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}

  deploy_hoodi_explorer:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      app: bridge
      component: hoodi-explorer
      env: ${{ inputs.env }}
      dockerfile: js/indexer/Dockerfile
      context: .
      paths_filter: |
        js/indexer/**
        js/common/**
        package.json
        yarn.lock
        lerna.json
        .yarnrc.yml
        .yarn/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}

  deploy_frontend:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      app: bridge
      component: frontend
      env: ${{ inputs.env }}
      dockerfile: js/frontend/Dockerfile
      context: .
      paths_filter: |
        js/frontend/**
        js/common/**
        js/bridge-js/**
        package.json
        yarn.lock
        lerna.json
        .yarnrc.yml
        .yarn/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}
