name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
      runs-on: kuberunner
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install Rust toolchain
          uses: actions-rs/toolchain@v1
        - name: Build
          run: cargo build --all-targets
        - name: Test
          run: cargo test
