name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: kuberunner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.1'
      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Build
        run: cargo build --release --all-targets
  lints:
    runs-on: kuberunner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.1'
      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run clippy
        run: cargo clippy --release --all-targets -- -D warnings $(cat .lints | cut -f1 -d"#" | tr '\n' ' ')
      - name: Run rustfmt
        run: cargo fmt -- --check
  tests:
    runs-on: kuberunner
    env:
      NAME: gear_node${{ github.run_id }}_${{ github.run_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.1'
      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run tests
        run: cargo test --release --all-targets
      - name: Run solidity tests
        run: |
          cd ethereum
          forge test
      - name: Pull & run Gear node container
        run: |
          docker pull ghcr.io/gear-tech/node:v1.6.2
          docker run --name $NAME --detach --rm --publish 127.0.0.1:9944:9944 ghcr.io/gear-tech/node:v1.6.2 gear --dev --tmp --rpc-external --log gear=debug,pallet_gear=debug,gwasm=debug
      - name: Run `erc20-relay-app` tests
        run: cargo test --release --package erc20-relay-app -- --nocapture --ignored || { exit_code=$?; if [ x$exit_code != x0 ]; then docker logs --details $NAME; docker stop $NAME; fi; exit $exit_code; }
      - name: Stop Gear node container (if any)
        continue-on-error: true
        run: docker stop $NAME
