name: Indexer

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'stg'
        type: choice
        options:
          - stg
          - prod
          - temp

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: indexer/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-indexer:${{ github.event.inputs.environment }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-indexer:${{ github.event.inputs.environment }}-${{ env.COMMIT_SHA }}

  deploy-to-k8s:
    needs: build-image
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Kubernetes
        uses: sergeyfilyanin/kubectl-aws-eks@master
        with:
          args: rollout restart deployment indexer-bridge-processor-eth-${{ github.event.inputs.environment }} indexer-bridge-processor-gear-${{ github.event.inputs.environment }} indexer-bridge-graphql-${{ github.event.inputs.environment }} -n gear-bridges

      - name: Check rollout status
        uses: sergeyfilyanin/kubectl-aws-eks@master
        with:
          args: get deployment -o name -n gear-bridges | xargs -n1 -t kubectl rollout status -n gear-bridges --timeout=120s
