name: CI indexer

on:
  pull_request:
    branches:
      - main
    paths:
      - indexer/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        working-directory: indexer
        run: npm install

      - name: Copy api files
        run: |
          mkdir -p indexer/assets
          cp api/ethereum/IERC20Manager.json api/ethereum/IMessageQueue.json indexer/assets

      - name: Build
        working-directory: indexer
        run: npm run build
